# Generated by Django 4.1.2 on 2022-11-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_rename_colour_product_color"),
    ]

    operations = [
        migrations.RenameField(model_name="buyer", old_name="pic4", new_name="pic",),
    ]
