# Generated by Django 4.1.2 on 2023-02-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0008_checkout_checkoutproducts"),
    ]

    operations = [
        migrations.RemoveField(model_name="checkoutproducts", name="checkout",),
        migrations.RemoveField(model_name="checkoutproducts", name="p",),
        migrations.DeleteModel(name="Checkout",),
        migrations.DeleteModel(name="CheckoutProducts",),
    ]
